import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
   # "~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"
  # "~/.config/alacritty/kanagawa/dragon.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin/catppuccin-latte.toml"
]
[env]
TERM= "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 0, y = 0}
opacity = 0.98
blur = true
# opt_as_alt = "Both"

[font]
size = 16
normal = {family = "MesloLGS NF", style = "Regular"}
# bold = {family = "MesloLGS NF", style = "Bold"}
# italic = {family = "MesloLGS NF", style = "Italic"}
# bold_italic = {family = "MesloLGS NF", style = "Bold Italic"}
builtin_box_drawing = true 





